spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: ${SUPABASE_USER} 
    password: ${SUPABASE_PASSWORD} 
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:main.sql
    
    
server:
  port: 8080
  
